[package]
name = "gml_log_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chompy = { git = "https://github.com/imlazyeye/chompy" }
itertools = "0.12"